# Generated by Django 5.2.7 on 2025-11-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(default='pythonuser', max_length=20)),
            ],
        ),
    ]
